### ISSUE TITLE
GMail is blocking access?

### ISSUE THREAD

**Issue by maebs** [f1shl/netflix-household-update#7]
hi all,

the script has been running beautifully for the past times, but as from today I keep getting this error:

`imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'
`
I tried to troubleshoot using:
-. incognito mode and login to gmail using the username and pass as in config.ini: PASS
-. IMAP is ON (as well as pop)
-. running a small script like so (testimap.py), but it still showing the same error:

```
import imaplib

imap_server = 'your_imap_server_here'  # e.g., 'imap.gmail.com' for Gmail
imap_port = 993
imap_username = 'your_email_here'
imap_password = 'your_password_here'

try:
    mail = imaplib.IMAP4_SSL(imap_server, imap_port)
    mail.login(imap_username, imap_password)
    print("Login successful!")
    mail.logout()
except imaplib.IMAP4.error as e:
    print(f"IMAP login failed: {e}")
```

I **know** that I have the correct username and correct password, but somehow logging in using Python script is a no go.

Any ideas? TIA.

**Comment by f1shl** [comment]
I just googled it and it seems that gmail requires an additional token, generated with OAuth2:
https://developers.google.com/identity/protocols/oauth2

It could be also a problem regarding 2FA. Have you activated it recently for your gmail account?

**Comment by maebs** [comment]
Well, that's the strange part; that OAuth2 thing with GMail was something from 2022, and your script has been working just fine without it... until today, at least for me.

But no, I explicitly disabled 2FA for this account and purpose. Any other idea?

**Comment by f1shl** [comment]
Yes, your are right.
Maybe it is worth to try OAuth2 for the script, should not hurt to use it anyway. If you have time you can do it and we can merge it. Otherwise I will try it this week.

**Comment by maebs** [comment]
OK, I got it working: enable 2FA, create app-specific password, modify my test script above with success, modify config.ini using the app specific pass, working. (again. yay!)

thanks for the pointers! (and your script)

**Comment by f1shl** [comment]
Great to here!
